/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author manum
 */
public class GraficaOrdenadaVista extends javax.swing.JFrame {

    /**
     * Creates new form GraficaOrdenadaVista
     */
    public GraficaOrdenadaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        grafica = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVelocidad = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        txtOrden = new javax.swing.JLabel();
        txtPasos = new javax.swing.JLabel();
        txtMinutos2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txtSegundos1 = new javax.swing.JLabel();
        txtMilisegundos1 = new javax.swing.JLabel();
        txtAlgirtmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiempo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, -1));

        grafica.setPreferredSize(new java.awt.Dimension(510, 310));

        javax.swing.GroupLayout graficaLayout = new javax.swing.GroupLayout(grafica);
        grafica.setLayout(graficaLayout);
        graficaLayout.setHorizontalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        graficaLayout.setVerticalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Orden:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pasos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Algoritmo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Velocidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        txtVelocidad.setBackground(new java.awt.Color(0, 0, 0));
        txtVelocidad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        txtVelocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelocidad.setText("null");
        txtVelocidad.setBorder(null);
        jPanel1.add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        txt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setText(":");
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 10, 20));

        txtOrden.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtOrden.setForeground(new java.awt.Color(255, 255, 255));
        txtOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtOrden.setText("null");
        jPanel1.add(txtOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 20));

        txtPasos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtPasos.setForeground(new java.awt.Color(255, 255, 255));
        txtPasos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPasos.setText("00");
        jPanel1.add(txtPasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 30, 20));

        txtMinutos2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtMinutos2.setForeground(new java.awt.Color(255, 255, 255));
        txtMinutos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMinutos2.setText("00");
        jPanel1.add(txtMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 30, 20));

        txt1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText(":");
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 10, 20));

        txtSegundos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtSegundos1.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSegundos1.setText("00");
        jPanel1.add(txtSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 30, 20));

        txtMilisegundos1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtMilisegundos1.setForeground(new java.awt.Color(255, 255, 255));
        txtMilisegundos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMilisegundos1.setText("00");
        jPanel1.add(txtMilisegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 30, 20));

        txtAlgirtmo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        txtAlgirtmo.setForeground(new java.awt.Color(255, 255, 255));
        txtAlgirtmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlgirtmo.setText("null");
        jPanel1.add(txtAlgirtmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaOrdenadaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaOrdenadaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaOrdenadaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaOrdenadaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaOrdenadaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel grafica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt1;
    public javax.swing.JLabel txtAlgirtmo;
    public javax.swing.JLabel txtMilisegundos1;
    public javax.swing.JLabel txtMinutos2;
    public javax.swing.JLabel txtOrden;
    public javax.swing.JLabel txtPasos;
    public javax.swing.JLabel txtSegundos1;
    public javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
