/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author manum
 */
public class OpcionVista extends javax.swing.JFrame {

    /**
     * Creates new form OpcionVista
     */
    public OpcionVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoOrdenamiento = new javax.swing.ButtonGroup();
        VelocidadOrdenamiento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAscendente = new javax.swing.JRadioButton();
        btnDescendente = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLento = new javax.swing.JRadioButton();
        btnNormal = new javax.swing.JRadioButton();
        btnRapido = new javax.swing.JRadioButton();
        btnOrdenamiento = new javax.swing.JComboBox<>();
        btnOrdenar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de ordenamiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        BtnAscendente.setBackground(new java.awt.Color(0, 0, 0));
        TipoOrdenamiento.add(BtnAscendente);
        BtnAscendente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        BtnAscendente.setForeground(new java.awt.Color(255, 255, 255));
        BtnAscendente.setSelected(true);
        BtnAscendente.setText("Ascendente");
        jPanel1.add(BtnAscendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnDescendente.setBackground(new java.awt.Color(0, 0, 0));
        TipoOrdenamiento.add(btnDescendente);
        btnDescendente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnDescendente.setForeground(new java.awt.Color(255, 255, 255));
        btnDescendente.setText("Descendente");
        btnDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescendenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 20, 120));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><center>Algoritmo de Ordenamiento</center><html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html><center>Velocidad de Ordenamiento</center><html>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 40));

        btnLento.setBackground(new java.awt.Color(0, 0, 0));
        VelocidadOrdenamiento.add(btnLento);
        btnLento.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnLento.setForeground(new java.awt.Color(255, 255, 255));
        btnLento.setSelected(true);
        btnLento.setText("lento");
        jPanel1.add(btnLento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnNormal.setBackground(new java.awt.Color(0, 0, 0));
        VelocidadOrdenamiento.add(btnNormal);
        btnNormal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnNormal.setForeground(new java.awt.Color(255, 255, 255));
        btnNormal.setText("normal");
        jPanel1.add(btnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnRapido.setBackground(new java.awt.Color(0, 0, 0));
        VelocidadOrdenamiento.add(btnRapido);
        btnRapido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnRapido.setForeground(new java.awt.Color(255, 255, 255));
        btnRapido.setText("rapido");
        jPanel1.add(btnRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        btnOrdenamiento.setBackground(new java.awt.Color(0, 0, 0));
        btnOrdenamiento.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnOrdenamiento.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(btnOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, 20));

        btnOrdenar.setBackground(new java.awt.Color(0, 102, 255));
        btnOrdenar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("Ordenar");
        btnOrdenar.setActionCommand("Ordenar");
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
        btnCancelar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescendenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton BtnAscendente;
    public javax.swing.ButtonGroup TipoOrdenamiento;
    public javax.swing.ButtonGroup VelocidadOrdenamiento;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JRadioButton btnDescendente;
    public javax.swing.JRadioButton btnLento;
    public javax.swing.JRadioButton btnNormal;
    public javax.swing.JComboBox<String> btnOrdenamiento;
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JRadioButton btnRapido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
